project:
  type: website
  output-dir: docs

execute:
  echo: false  

website:
  title: "Partage26"
  navbar:
    left:
      - href: index.qmd
        text: Home
    right:
      - icon: github
        href: https://github.com/

format:
  html:
    theme: lumen
    css: styles.css
    toc: true

bibliography: references.bib

editor: visual
